routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'frontController@index');
Route::get('logout', 'Auth\LoginController@logout');
Route::resource('log', 'LogController');

Route::get('createTableValidacionEstudios', function () {
    return view('createTableValidacionEstudios');
});


	Route::group(['middleware' => 'auth'], function(){
		Route::get('admin', function(){ return view('admin'); });
		Route::resource('usuarios', 'usuarioController');
		Route::resource('clientes', 'clienteController');
		Route::get('/trackins/cliente/{id}', 'clienteController@getcliente');
		Route::resource('paises', 'paisController');
		Route::resource('subrubros', 'subrubroController');
		Route::resource('departamentos', 'departamentoController');
		Route::resource('cargos', 'cargoController');
		Route::resource('rubros', 'rubroController');
		Route::resource('empresas', 'empresaController');
		Route::resource('estudios', 'estudioController');
		Route::resource('encuestas', 'encuestaController');
		Route::resource('bitacoras', 'bitacoraController');
		Route::resource('benchmarks', 'benchmarkController');
		Route::resource('mails', 'mailController');
		Route::resource('promotions', 'promotionController');
		Route::resource('carousels', 'carouselController');
		Route::resource('uploadimagenes', 'uploadimagenesController');
		Route::get('cargarimg/{id}', 'uploadimagenesController@create');
		Route::resource('trackins', 'trackinController');
		Route::resource('reg_cargas', 'reg_cargasController');
		Route::resource('estamentos', 'estamentoController');
		Route::resource('areas', 'areaController');
		Route::resource('tipo_areas', 'tipo_areaController');
		Route::resource('tipo_causales', 'tipo_causalController');
		Route::resource('causales', 'causalController');
		Route::resource('bench_indicadores', 'b_indicadoresController');
        Route::get('/bench_indicadores/cliente/{id}', 'clienteController@getcliente');
        Route::get('usuarios/excel', 'usuarioController@excel');
        Route::get('/estudios/cliente/{id}', 'clienteController@getcliente');
        Route::resource('/estudio_validate','estudio_validacionController');
        Route::get('estudio_validate/{id}', 'clienteController@getcliente');
        Route::get('estudio_validate/delete/{id}','estudio_validacionController@destroy');
        Route::post('getClientes','clienteController@actualizarClientes');
        Route::post('getEstudios','estudioController@actualizarEstudios');


	});

resources/views/causales/edit.blade.php
@extends('layouts.principal')
@section('content')
    <div class="row wrapper border-bottom white-bg page-heading">
        <div class="col-lg-10">
            <h2>Dashboard &Aacute;rea</h2>
            <ol class="breadcrumb">
                <li>Home</li>
                <li>Formulario</li>
                <li class="active"><strong>Editar &Aacute;rea</strong></li>
            </ol>
        </div>
    </div>

    <div class="wrapper wrapper-content animated fadeInRight">
    <div class="row">            
        <div class="col-lg-5">
            <div class="ibox float-e-margins">
                <div class="ibox-title">
                    <h5>Editar &Aacute;rea</h5>
                </div>
                <div class="ibox-content">
                	@include('alerts.request')
    				{!! Form::model($area,['route'=> ['areas.update',$area->id], 'method'=>'PUT']) !!}
                        <div class="form-group">
                            {!! Form::label('Tipo de Area') !!}
                            {!! Form::select('tipo_area', $tipo_areas, null,['class'=>'form-control']) !!}
                        </div>    	    			
                        <div class="form-group">
                            {!! Form::label('Nombre del Area') !!}
                            {!! Form::text('area', null, ['placeholder'=>'&Aacute;rea', 'class'=>'form-control']) !!}
                        </div>
                        <div class="form-group">
                            {!! Form::label('Estatus del Area') !!}
                            {!! Form::select('status', ['1' => 'Activo', '0' => 'Inactivo'], '1',['class' => 'form-control']) !!}
                        </div>
    	            	{!! Form::submit('Actualizar', ['class' => 'btn btn-primary block full-width m-b']) !!}				            
    				{!! Form::close() !!}
    				@if ( Auth::user()->rol == 1)
    				{!! Form::model($area,['route'=> ['areas.destroy',$area->id], 'method'=>'DELETE']) !!}
    	    			
    	            	{!! Form::submit('Eliminar', ['class' => 'btn btn-danger block full-width m-b']) !!}				            
    				{!! Form::close() !!}
                    @endif
                </div>
            </div>
        </div>
    </div>
    </div>
@stop

resources/views/causales/index.blade.php
@extends('layouts.principal')

@section('styles')
<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.19/css/jquery.dataTables.css">
@endsection

@section('content')
    <div class="row wrapper border-bottom white-bg page-heading">
        <div class="col-lg-10">
            <h2>Dashboard Causales</h2>
            <ol class="breadcrumb">
                <li>Home</li>
                <li>Formulario</li>
                <li class="active"><strong>Causales</strong></li>
            </ol>
        </div>
    </div>

    @if(Session::has('message'))
    <div class="alert alert-success alert-dismissible" role="alert">
      <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
      {{ Session::get('message') }}
    </div>
    @endif

    <div class="row">
        <div class="col-lg-4">
            <div class="ibox float-e-margins">
                <div class="ibox-title">
                    <h5>Crear Causal</h5>
                </div>
                <div class="ibox-content">
                    @include('alerts.request')
                    {!! Form::open(['route'=> 'causales.store', 'method'=>'POST']) !!}
                        <div class="form-group">
                            {!! Form::label('Tipo de Causal') !!}
                            {!! Form::select('tipo_causal', $tipo_causales, null,['class'=>'form-control']) !!}
                        </div>                    
                        <div class="form-group">
                            {!! Form::label('Nombre de la Causal') !!}
                            {!! Form::text('causal', null, ['placeholder'=>'Causal', 'class'=>'form-control']) !!}
                        </div>
                        <div class="form-group">
                            {!! Form::label('Estatus de la Causal') !!}
                            {!! Form::select('status', ['1' => 'Activo', '0' => 'Inactivo'], '1',['class' => 'form-control']) !!}
                        </div>
                        {!! Form::submit('Registrar', ['class' => 'btn btn-primary block full-width m-b']) !!}                          
                    {!! Form::close() !!}
                </div>
            </div>
        </div>
        <div class="col-lg-7">
            <div class="ibox float-e-margins">
                <div class="ibox-title">
                    <h5>Listado de Causales</h5>
                    <div class="ibox-tools">
                        <a class="collapse-link">
                            <i class="fa fa-chevron-up"></i>
                        </a>
                        <a class="close-link">
                            <i class="fa fa-times"></i>
                        </a>
                    </div>
                </div>
                <div class="ibox-content">
                    <table id="table_id" class="display">
                        <thead>
                        <tr>
                            <th>Tipo de &Aacute;rea</th>
                            <th>&Aacute;rea</th>
                            <th>Estatus</th>
                            <th>Acci&oacute;n</th>
                        </tr>
                        </thead>
                        <tbody>
                        @foreach($causales as $causal)                        
                        <tr>
                            <td><small>{{ $causal->tipo }}</small></td>
                            <td><small>{{ $causal->causal }}</small></td>
                            <td>@if ( $causal->status == 1) <p class="text-success">Activo</p> @else <p class="text-danger">Inactivo</p> @endif</td>
                            <td>{!! link_to_route('causales.edit', $title = 'Editar', $parameters = $causal->id, $attributes = ['class'=>'btn btn-primary']) !!}</td>
                        </tr>                        
                        @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
@endsection
@section('javascripts')
    <script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.js"></script>
    <script>
        $(document).ready( function () {
            $('#table_id').DataTable();
        } );
    </script>
@endsection