routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'frontController@index');
Route::get('logout', 'Auth\LoginController@logout');
Route::resource('log', 'LogController');

Route::get('createTableValidacionEstudios', function () {
    return view('createTableValidacionEstudios');
});


	Route::group(['middleware' => 'auth'], function(){
		Route::get('admin', function(){ return view('admin'); });
		Route::resource('usuarios', 'usuarioController');
		Route::resource('clientes', 'clienteController');
		Route::get('/trackins/cliente/{id}', 'clienteController@getcliente');
		Route::resource('paises', 'paisController');
		Route::resource('subrubros', 'subrubroController');
		Route::resource('departamentos', 'departamentoController');
		Route::resource('cargos', 'cargoController');
		Route::resource('rubros', 'rubroController');
		Route::resource('empresas', 'empresaController');
		Route::resource('estudios', 'estudioController');
		Route::resource('encuestas', 'encuestaController');
		Route::resource('bitacoras', 'bitacoraController');
		Route::resource('benchmarks', 'benchmarkController');
		Route::resource('mails', 'mailController');
		Route::resource('promotions', 'promotionController');
		Route::resource('carousels', 'carouselController');
		Route::resource('uploadimagenes', 'uploadimagenesController');
		Route::get('cargarimg/{id}', 'uploadimagenesController@create');
		Route::resource('trackins', 'trackinController');
		Route::resource('reg_cargas', 'reg_cargasController');
		Route::resource('estamentos', 'estamentoController');
		Route::resource('areas', 'areaController');
		Route::resource('tipo_areas', 'tipo_areaController');
		Route::resource('tipo_causales', 'tipo_causalController');
		Route::resource('causales', 'causalController');
		Route::resource('bench_indicadores', 'b_indicadoresController');
        Route::get('/bench_indicadores/cliente/{id}', 'clienteController@getcliente');
        Route::get('usuarios/excel', 'usuarioController@excel');
        Route::get('/estudios/cliente/{id}', 'clienteController@getcliente');
        Route::resource('/estudio_validate','estudio_validacionController');
        Route::get('estudio_validate/{id}', 'clienteController@getcliente');
        Route::get('estudio_validate/delete/{id}','estudio_validacionController@destroy');
        Route::post('getClientes','clienteController@actualizarClientes');
        Route::post('getEstudios','estudioController@actualizarEstudios');


	});

app/b_indicadores.php
<?php

namespace kpi;

use Illuminate\Database\Eloquent\Model;
use DB;

class b_indicadores extends Model
{
    protected $table = 'b_indicadores';

    protected $fillable = [
        'empresa', 'usuario', 'historial_carga', 'modalidad', 'plan', 'es_admin', 'url_bi', 'status',
    ];

    public static function b_indicadores(){
        return DB::table('b_indicadores')
            ->join('empresas','empresas.id','=','b_indicadores.empresa')
            ->join('clientes', 'clientes.id', '=', 'b_indicadores.usuario')
            ->select('b_indicadores.*','empresas.empresa', 'clientes.nombre', 'clientes.apellido')
            ->get();
    }
}

app/Http/Controllers/b_indicadoresController.php
<?php

namespace kpi\Http\Controllers;

use Illuminate\Http\Request;
use kpi\b_indicadores;
use kpi\Http\Requests\B_IndicadoresUpdateRequest;
use Redirect;
use Session;
use kpi\clientes;
use kpi\empresa;
use kpi\trackin;
use Mail;
use DB;

class b_indicadoresController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $b_indicadores = b_indicadores::b_indicadores();
        return view('b_indicadores.index', compact('b_indicadores'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $empresas = empresa::pluck('empresa','id');
        return view('b_indicadores.crear', compact('empresas'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $usuarios = $_POST["id_cliente"];


        $enviar_mail = $request->enviar_mail;


        if ($enviar_mail == 'SI')
        {
            foreach ($usuarios as $usuario)
            {

                $query = db::insert("INSERT INTO b_indicadores (empresa, historial_carga, modalidad, plan, es_admin, url_bi, status, created_at, usuario) VALUES ('$request->empresa','$request->historial_carga','$request->modalidad', '0', '$request->es_admin','$request->url_bi','$request->status',NOW(),'{$usuario}')");

                $id_cliente = $usuario;
                $results = DB::select("SELECT email FROM clientes WHERE id = '$id_cliente'");
                $results_mail = $results[0];
                $mail_cliente=$results_mail->email;

                Mail::send('emails.nuevoKpianalytics',$request->all(), function($msj) use ($mail_cliente){
                    $msj->subject('Registro Benchmarks de Indicadores - KPI Estudios');
                    $msj->to($mail_cliente);
                });
            }
            Session::flash('message', 'Servicio y Correos enviados Correctamente');
            return Redirect::to('bench_indicadores');
        }else{

                $query = db::insert("INSERT INTO b_indicadores (empresa, historial_carga, modalidad, plan, es_admin, url_bi, status, created_at, usuario) VALUES ('$request->empresa','$request->historial_carga','$request->modalidad', '0', '$request->es_admin','$request->url_bi','$request->status',NOW(),'{$usuarios}')");

            Session::flash('message', 'Servicio Activado Correctamente');
            return Redirect::to('bench_indicadores');
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $b_indicadores = b_indicadores::find($id);
        $clientes = clientes::select(DB::raw("CONCAT(nombre,' ',apellido) AS nombre"),'id')->where('status', 1)->pluck('nombre', 'id');
        return view('b_indicadores.edit',['b_indicadores'=>$b_indicadores])->with(compact('clientes'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update($id, B_IndicadoresUpdateRequest $request)
    {
        $b_indicadores = b_indicadores::find($id)->update($request->all());
        Session::flash('message', 'Servicio de Benchmark de Indicadores editado correctamente');
        return Redirect::to('bench_indicadores');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $trackin = b_indicadores::find($id);
        $trackin->delete();

        Session::flash('message', 'Servicio Benchmark de Indicadores eliminado correctamente');
        return Redirect::to('bench_indicadores');
    }
}

resources/views/b_indicadores/crear.blade.php
@extends('layouts.principal')

@section('styles')
<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.19/css/jquery.dataTables.css">
@endsection

@section('content')
    <div class="row wrapper border-bottom white-bg page-heading">
        <div class="col-lg-10">
            <h2>Benchmark de Indicadores</h2>
            <ol class="breadcrumb">
                <li>Home</li>
                <li>Formulario</li>
                <li class="active"><strong>Benchmark de Indicadores</strong></li>
            </ol>
        </div>
    </div>

    <div class="row">
        <div class="col-lg-4">
            <div class="ibox float-e-margins">
                <div class="ibox-title">
                    <h5>Activar Usuario</h5>
                </div>
                <div class="ibox-content">
                    @include('alerts.request')
                    {!! Form::open(['route'=> 'bench_indicadores.store', 'method'=>'POST', 'files' => true]) !!}
                        <div class="form-group">
                            <input type="checkbox" name="enviar_mail" value="SI"> &nbsp;{!! Form::label('Enviar correo de Activaci&oacute;n de Servicio') !!}
                        </div>

                    <div class="form-group">
                        <font color="red">* </font>{!! Form::label('Seleccionar Empresa') !!}
                        {!! Form::select('empresa',$empresas,null,['placeholder'=>'Selecciona','class'=>'form-control', 'id'=>'empresa', 'onchange' => 'actualizar_cliente()']) !!}
                    </div>
                    <div class="form-group">
                        <font color="red">* </font>{!! Form::label('Seleccionar Usuario') !!}
                        {!! Form::select('id_cliente',[],null,['placeholder'=>'Selecciona','class'=>'form-control', 'id'=>'cliente', 'required']) !!}
                    </div>



                        <div class="form-group">
                            <font color="red">* </font>{!! Form::label('Historial de Carga') !!}
                            {!! Form::select('historial_carga', ['placeholder'=>'Selecciona', '1' => 'Activo', '0' => 'Inactivo'], null,['class' => 'form-control']) !!}
                        </div>
                        <div class="form-group">
                            <font color="red">* </font>{!! Form::label('Modalidad') !!}
                            {!! Form::select('modalidad', ['placeholder'=>'Selecciona', '1' => 'Paga', '0' => 'Gratis'], null,['class' => 'form-control']) !!}
                        </div>
                        <div class="form-group">
                            <font color="red">* </font>{!! Form::label('Administrador') !!}
                            {!! Form::select('es_admin', ['placeholder'=>'Selecciona', '1' => 'Si', '0' => 'No'], null,['class' => 'form-control']) !!}
                        </div>
                        <div class="form-group">
                            <font color="red">* </font>{!! Form::label('URL Informe') !!}
                            {!! Form::text('url_bi', null, ['placeholder'=>'Link del Informe del Cliente', 'class'=>'form-control']) !!}
                        </div>
                        <div class="form-group">
                            <font color="red">* </font>{!! Form::label('Estatus del Servicio') !!}
                            {!!Form::select('status', ['placeholder'=>'Selecciona', '1' => 'Activo', '0' => 'Inactivo'], null, ['class'=>'form-control'] )!!}
                        </div>
                        {!! Form::submit('Activar', ['class' => 'btn btn-primary block full-width m-b']) !!}                          
                    {!! Form::close() !!}
                </div>
            </div>
        </div>        
    </div>

@endsection
@section('javascripts')
{!!Html::script('js/dropdown.js')!!}
{!!Html::script('https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/js/select2.min.js')!!}
<script>
    // In your Javascript (external .js resource or <script> tag)
$(document).ready(function() {
    $('.basic-single').select2();
});
</script>
@endsection

resources/views/b_indicadores/edit.blade.php
@extends('layouts.principal')

@section('styles')
<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.19/css/jquery.dataTables.css">
@endsection

@section('content')
    <div class="row wrapper border-bottom white-bg page-heading">
        <div class="col-lg-10">
            <h2>Dashboard Benchmark de Indicadores</h2>
            <ol class="breadcrumb">
                <li>Home</li>
                <li>Formulario</li>
                <li class="active"><strong>Benchmark de Indicadores</strong></li>
            </ol>
        </div>
    </div>

    @if(Session::has('message'))
    <div class="alert alert-success alert-dismissible" role="alert">
      <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
      {{ Session::get('message') }}
    </div>
    @endif

    <div class="row">
        <div class="col-lg-4">
            <div class="ibox float-e-margins">
                <div class="ibox-title">
                    <h5>Editar Servicio Benchmark de Indicadores</h5>
                </div>
                <div class="ibox-content">
                    @include('alerts.request')
                    {!! Form::model($b_indicadores,['route'=> ['bench_indicadores.update',$b_indicadores->id], 'method'=>'PUT', 'files' => true]) !!}
                        <div class="form-group">
                            {!! Form::label('Usuario') !!}
                            {!! Form::select('usuario',  $clientes, null,['class'=>'form-control']) !!}
                        </div>
                        <div class="form-group">
                            {!! Form::label('Historial de Carga') !!}
                            {!! Form::select('historial_carga', ['1' => 'Activo', '0' => 'Inactivo'], $b_indicadores->historial_carga,['class' => 'form-control']) !!}
                        </div>
                        <div class="form-group">
                            {!! Form::label('Modalidad') !!}
                            {!! Form::select('modalidad', ['1' => 'Paga', '0' => 'Gratis'], $b_indicadores->modalidad,['class' => 'form-control']) !!}
                        </div>
                        <div class="form-group">
                            {!! Form::label('Administrador') !!}
                            {!! Form::select('es_admin', ['1' => 'Si', '0' => 'No'], $b_indicadores->es_admin,['class' => 'form-control']) !!}
                        </div> 
                        <div class="form-group">
                            {!! Form::label('Dashboard') !!}
                            {!! Form::text('url_bi', null,['class'=>'form-control']) !!}
                        </div>                                                 
                        <div class="form-group">
                            {!! Form::label('Estatus del Servicio') !!}
                            {!! Form::select('status', ['1' => 'Activo', '0' => 'Inactivo'], $b_indicadores->status,['class' => 'form-control']) !!}
                        </div>
                        {!! Form::submit('Actualizar', ['class' => 'btn btn-primary block full-width m-b']) !!}                          
                    {!! Form::close() !!}
                    @if ( Auth::user()->rol == 1)
                    {!! Form::model($b_indicadores,['route'=> ['bench_indicadores.destroy',$b_indicadores->id], 'method'=>'DELETE']) !!}
                        
                        {!! Form::submit('Eliminar', ['onClick'=>"javascript: return confirm('¿Esta seguro que desea eliminarlo?');",'class' => 'btn btn-danger block full-width m-b']) !!}
                    {!! Form::close() !!}
                    @endif
                </div>
            </div>
        </div>        
    </div>
@stop

resources/views/b_indicadores/index.blade.php
@extends('layouts.principal')

@section('styles')
<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.19/css/jquery.dataTables.css">
@endsection

@section('content')
    <div class="row wrapper border-bottom white-bg page-heading">
        <div class="col-lg-10">
            <h2>Dashboard Benchmarks Indicadores</h2>
            <ol class="breadcrumb">
                <li>Home</li>
                <li>Formulario</li>
                <li class="active"><strong>Benchmarks Indicadores</strong></li>
            </ol>
        </div>
    </div>

    @if(Session::has('message'))
    <div class="alert alert-success alert-dismissible" role="alert">
      <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
      {{ Session::get('message') }}
    </div>
    @endif

    <div class="col-lg-12">
        <div class="ibox float-e-margins">
            <div class="ibox-title">
                <h5>Listado de Clientes</h5>
                <div class="ibox-tools">
                    <a class="collapse-link">
                        <i class="fa fa-chevron-up"></i>
                    </a>
                    <a class="close-link">
                        <i class="fa fa-times"></i>
                    </a>
                </div>
            </div>
            <div class="ibox-content">
                <table id="table_id" class="display">
                    <thead>
                        <tr>
                            <th>Id Registro</th>
                            <th>Empresa</th>
                            <th>Cliente</th>
                            <th>Administrador</th>
                            <th>Historial de Carga</th>
                            <th>Modalidad</th>
                            <th>Informe</th>
                            <th>Estatus</th>
                            <th>Acci&oacute;n</th>
                        </tr>
                    </thead>
                    
                    <tbody>
                        @foreach($b_indicadores as $b)
                        <tr>
                            <td>{{ $b->id }}</td>
                            <td>{{ $b->empresa }}</td>
                            <td>{{ $b->nombre }} {{ $b->apellido }}</td>
                            <td>@if($b->es_admin == 1) Si @else No @endif</td>
                            <td>@if($b->historial_carga == 1) Si @else No @endif</td>
                            <td>@if($b->modalidad == 1) Paga @else Gratis @endif</td>
                            @if(!empty($b->url_bi)) <td><a href="{!! $b->url_bi !!}" target="_blank"><button class="btn btn-primary">Ver Informe</button></a></td> @else <td> <p class="text-danger">Sin Informe</p> @endif
                            <td>@if($b->status == 1) <p class="text-success">Activo</p> @else <p class="text-danger">Inactivo</p> @endif</td>
                            <td>{!! link_to_route('bench_indicadores.edit', $title = 'Editar', $parameters = $b->id, $attributes = ['class'=>'btn btn-primary']) !!}</td>
                        </tr>
                        @endforeach
                    </tbody>                        
                </table>                    
            </div>
        </div>
    </div>
@endsection

@section('javascripts')
    <script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.js"></script>
    <script>

        $(document).ready(function() {
            $('#table_id').DataTable( {
                "lengthMenu": [[100, 50, 20, -1], [100, 50, 20, "Todos"]]
            } );
        } );
    </script>
@endsection